# Generated by Django 3.2.6 on 2021-08-18 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, unique=True)),
                ('book_writer', models.CharField(max_length=200)),
                ('book_date', models.DateField(default=django.utils.timezone.now)),
                ('book_pay', models.IntegerField(default=0)),
                ('book_oview', models.TextField(default='', null=True)),
            ],
        ),
    ]
