# Generated by Django 3.2.5 on 2021-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
