# Generated by Django 3.2.5 on 2021-08-04 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 15, 10, 10, 90755, tzinfo=utc)),
        ),
    ]
