# Generated by Django 3.2.5 on 2021-08-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_subject_subject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(default=20),
        ),
    ]
