# Generated by Django 3.2.6 on 2021-08-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_student_student_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_tel',
            field=models.CharField(max_length=200),
        ),
    ]
