# Generated by Django 3.2.6 on 2021-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_subject_subject_ovew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_ovew',
            field=models.TextField(default='', null=True),
        ),
    ]
