# Generated by Django 3.2.6 on 2021-08-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mem_id', models.CharField(max_length=200, unique=True)),
                ('Mem_pwd', models.CharField(max_length=200)),
                ('Mem_name', models.CharField(max_length=200)),
            ],
        ),
    ]
